### ISSUE TITLE
Ensure creating services tutorial covers Service paradigms

### ISSUE THREAD

**Issue by hinerm** [imagej/tutorials#21]
Rarely when implementing a service do we directly extend 'AbstractService'.. instead we usually write a 'Handler' or 'Singleton' etc..

Since we have interfaces and abstract classes for common service patterns, we should advertise them!

**Comment by ctrueden** [comment]
A tutorial on creating custom services in the various SciJava service paradigms is ultimately desirable. But the number of developers who will need to do this is orders of magnitude smaller than the ones who want to consume the existing services, and/or create plugins of more common types like `Command` and `Op`. I am going to close this issue for now, due to lack of urgent need. Some day, in response to user demand, we can create/augment an appropriate tutorial notebook (as of this writing, it would be called "Writing Service plugins" in "Extending ImageJ").
