### ISSUE TITLE
Detection area

### ISSUE THREAD

**Issue by amounTr** [imagej/tutorials#42]
Hello,
I would like to apply a region detection on pictures of greenery tiles. I tried with a plugin growing region method and also  the thresholding  but the obtained results were bad. Please could you give me some other solutions allowing me to detect these areas of greenness.

This is an example picture:

![img-320](https://user-images.githubusercontent.com/30657224/28873614-b421b3fa-778e-11e7-864e-43f874192cd9.jpg)

Thank you.

**Comment by imagejan** [comment]
@amounTr you should post your question on the [ImageJ forum](http://forum.imagej.net/). The github issues page here is really only about tracking issues with the current tutorials source code, whereas the forum has a much wider audience and it's more likely that you get an answer over there.
I'm closing this issue here.

**Comment by imagejan** [comment]
I just saw that you _also_ posted this in https://github.com/imagej/imagej/issues/174, so I guess you got the message :)
